import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font/sans'
import Link from 'next/link'
import { Search, ShoppingCart, User } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Navbar() {
  return (
    <header className='bg-green-700 text-white p-4'>
      <div className='container mx-auto flex justify-between items-center'>
        <h1 className='text-2xl font-bold'>
          <Link href='/'>GreenCart</Link>
        </h1>
        <nav className='hidden md:flex space-x-4'>
          <a href='#' className='hover:text-green-200 transition-colors'>
            Home
          </a>
          <a href='#' className='hover:text-green-200 transition-colors'>
            Shop
          </a>
          <a href='#' className='hover:text-green-200 transition-colors'>
            About
          </a>
        </nav>
        <div className='flex items-center space-x-4'>
          <div className='relative'>
            <input
              type='text'
              placeholder='Search products...'
              className='pl-8 pr-4 py-2 rounded-full bg-green-600 text-white placeholder-green-200 focus:outline-none focus:ring-2 focus:ring-green-400'
            />
            <Search className='absolute left-2 top-1/2 transform -translate-y-1/2 text-green-200' />
          </div>
          <button
            className='relative p-2 hover:bg-green-600 rounded-full transition-colors'
            aria-label='Shopping Cart'
          >
            <Link href='/cart'>
              <ShoppingCart />
              <span className='absolute top-0 right-0 bg-yellow-400 text-xs rounded-full h-5 w-5 flex items-center justify-center'>
                3
              </span>
            </Link>
          </button>
          <button
            className='p-2 hover:bg-green-600 rounded-full transition-colors'
            aria-label='User Profile'
          >
            <Link href='/account'>
              <User />
            </Link>
          </button>
        </div>
      </div>
    </header>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${GeistSans.className} antialiased`}>
        <div className='min-h-screen'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
